--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FrozenArea/QueryServer
build-by-default: true
branches:
- master
projects:
  QueryServer:
    path: ""
    libs:
      - src: jasonw4331/libpmquery/libpmquery
        version: 1.0.0
...
