--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhanaz-pm-pl/QueryServer
build-by-default: true
branches:
- master
projects:
  QueryServer:
    path: ""
    lint:
      phpstan: false
...
