---
name: QueryServer
version: 0.0.1
api: 4.0.0
main: NhanAZ\QueryServer\Main
src-namespace-prefix: NhanAZ\QueryServer
website: https://github.com/NhanAZ
description: Allow querying some other servers information
commands:
  query:
    aliases: [qr]
    permission: query.cmd
    description: Querying some other server's information
    usage: /query <domain/ip:port> to query certain server information
    permission-message: §e>§c You do not have permission to use this command!
  querys:
    aliases: [qrs]
    permission: querys.cmd
    description: Querying some other server's information (Backup method)
    usage: "/querys <domain/ip : port> to query certain server information"
    permission-message: §e>§c You do not have permission to use this command!
permissions:
  query.cmd:
    default: op
    description: Allow querying some other servers information
  querys.cmd:
    default: op
    description: Allow querying some other servers information (Backup method)
...
